language: java
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
deploy:
  provider: heroku
  api_key:
    secure: jWeY0fruCdsu+DDf/0k1UBnCqTHRrs2f+ulH7Jdc8RF/ysfg625l8wuEAbwzsltgxJUI9OXA4coJIl2mPmk0p+7BLBPUYyqZhDVFop6dZ3shZCL0bcFZaNAlkZ24PlkSrkESPgHWhMx4TOGYrkK2dx2fqVixaWWKNjzFEuxUM7FOcD/3rsTUqgsy/coQAHX0qw2mFzKdQjhSZS//2Nwi6sOQ7+VOID8MDDkbx9r3AtaST9q9Ge+bQFaSNYTCHSurIZFyPZveC0nqyOQT0fF5/Wew1WsihqOWZkDnwV3YP8/k3C76A7VFZOlkT4rR3wP8qm0OBU22oxb/eAYspYLfNheJ0ZQzrc69TjIP8hBumGtZ8mO9kMGmcSkTvtDoCAodQ3ef8lYnarwPb9fR5lEnkYe8gf+tu6U96NYMdpwV7rps5Ru2QEUZKWwksCo9DPFoJzXjB3O8PFaCg6Ec+Sp51p9Af13cIG5Vzc8Ajjf19X6qYUXn8zOqCJWKC//snLrd1/Hc32pVv8MrQ3mmqR0PM04ArulffxiUN2vDTS38XWmVOtlccqBRIB5w316Ll3kwILRn1g52fAW47tfEBM6tv2+7IpHlxe1OM7J9dLHqSQfdlTAtN8hPYYNYRosZc+Xxiy2hvAjAiMrzUILutxQJXy3NRH8on2Ti8iBfgRhQK/k=
  app: TicTacToe
  on:
    repo: hedinnh/TicTacToe
